# Generated by Django 3.1.1 on 2021-06-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210531_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='progress',
            field=models.CharField(blank=True, default='Started', max_length=800),
        ),
    ]
